apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hello-openshift-02-cqrs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jdavis-se-jboss-tenant/hello-openshift-02-web/hello-openshift-02-cqrs@sha256:c598e5395583a55334394d56963ab6d7123aafb7282a6a6a276bef831cf10889
        name: my-java-quarkus
        resources: {}
status: {}
