apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-openshift-02-ftp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-openshift-02-ftp
    app.kubernetes.io/part-of: hello-openshift-02-web
  name: hello-openshift-02-ftp
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: hello-openshift-02-ftp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: hello-openshift-02-ftp
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jdavis-se-jboss-tenant/hello-openshift-02-web/hello-openshift-02-ftp@sha256:07d60629a9880643833257140d80d20036b4e30f9ef735a520f55790f1a1b135
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
