apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-openshift-02-cqrs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-openshift-02-cqrs
    app.kubernetes.io/part-of: hello-openshift-02-web
  name: hello-openshift-02-cqrs
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: hello-openshift-02-cqrs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: hello-openshift-02-cqrs
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jdavis-se-jboss-tenant/hello-openshift-02-web/hello-openshift-02-cqrs@sha256:c598e5395583a55334394d56963ab6d7123aafb7282a6a6a276bef831cf10889
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
