apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hello-openshift-02-ftp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jdavis-se-jboss-tenant/hello-openshift-02-web/hello-openshift-02-ftp@sha256:07d60629a9880643833257140d80d20036b4e30f9ef735a520f55790f1a1b135
        name: my-java-quarkus
        resources: {}
status: {}
